### ISSUE TITLE
How to extract key for `key.txt`

### ISSUE THREAD

**Issue by lorecast162** [dmynerd78/switcheroo-lite#1]
Hello,
I've been looking on clearer info on how to extract this key from capsrv but wasn't able to find any info until now.
I tried extracting capsrv's NCA from my firmware dump, decompressing the main NSO0 from that and loading the output into a hex editor but the offset is waaay too big...
Not to mention that even if I _did_ get to that offset I couldn't see anything about that key's size.
To do the extraction I used [this](https://www.psx-place.com/threads/decrypting-switch-firmware-updates-a-basic-howto.35792/) post.
Do you remember something about this? Did I follow the wrong steps to get capsrv's NSO? Am I missing something?

**Comment by dmynerd78** [comment]
Sorry for the late reply for some reason I missed the email. I no longer have access to that Switch, so I'm not sure of the entire process. I do remember I used this issue as a jump start https://github.com/s1cp/nxshot/issues/42
I also updated the gameids.json file with new items from nswdb.
